/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption } from '@app/util'
import rootMixins from '@internal/root-mixins'
import components from '@internal/layout-components'
import LayoutDistributor from '@app/components/LayoutDistributor.vue'

injectComponentOption(LayoutDistributor, 'mixins', rootMixins)
injectComponentOption(LayoutDistributor, 'components', components)
export const routes = [,
  {
    path: '*',
    component: LayoutDistributor
  }
]